#!/usr/bin/env bash

if [ ! -d "$SNAP_USER_DATA/Mudream.online" ]; then
    mv -v "$SNAP/Mudream.online" \
       "$SNAP_USER_DATA"
fi

cd $SNAP_USER_DATA/Mudream.online

$SNAP/opt/wine-stable/bin/wine PlayMudream.exe
