version: "7.0"
name: mudream-online
title: MuDream.online
summary: Unofficial Mudream.online Snap Package
description: |
  MuDream Online offers a private server experience based on the classic MMORPG
  MU Online. The game has a clear progression system. New content, challenges,
  and events arrive in stages. This gives you fresh goals to complete over time.

confinement: strict
base: core24
grade: stable

package-repositories:
  - type: apt
    url: https://dl.winehq.org/wine-builds/ubuntu
    suites: [noble]
    components: [main]
    architectures: [amd64, i386]
    key-id: D43F640145369C51D786DDEA76F1A20FF987672F

plugs:
  shmem:
    interface: shared-memory
    private: true
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404

environment:
  WINEARCH: "wow64"
  WINEPREFIX: $SNAP_USER_DATA/wineprefix
  WINEDLLOVERRIDES: "winex11.drv=;"
  WINE_NTSYNC: "1"
  DRI_PRIME: "1"

apps:
  mudream-online:
    command-chain:
      - bin/gpu-2404-wrapper
    command: usr/bin/mudream-online-wrapper
    extensions: [gnome]
    plugs:
      - home
      - shmem
      - network
      - network-bind
      - x11
      - wayland
      - opengl
      - audio-playback
      - hardware-observe
      - gpu-2404

parts:
  wine:
    plugin: nil
    stage-packages:
      - winehq-stable
      - winetricks
  mudream-online:
    plugin: nil
    source: ./snap/local/src
    override-build: |
      craftctl default

      echo "==> Installing build dependencies..."
      DEBIAN_FRONTEND=noninteractive apt-get update
      DEBIAN_FRONTEND=noninteractive apt-get install -y unrar

      echo "==> Download the Game archive..."
      curl "https://drive.usercontent.google.com/download?id=1DtYQu4rGQbgfvyFRS31mZwhiTK7JrciL&confirm" -o Mudream.online.rar

      echo "==> Unpacking the Game archive..."
      unrar x -o+ Mudream.online.rar

      echo "==> Moving files into place..."
      find Mudream.online -type f -exec install -Dm 755 "{}" "${CRAFT_PART_INSTALL}/{}" \;
      mkdir -p ${CRAFT_PART_INSTALL}/usr/bin
      install -Dm755 mudream-online-wrapper ${CRAFT_PART_INSTALL}/usr/bin/
  gpu-2404:
    after: [mudream-online]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
